services:
  mq-det:
    build: .
    # modern compose doesn't need the top-level "version" key; removing silences the warning
    runtime: nvidia
    shm_size: "2g"
    ipc: host  # Fix: Share host IPC namespace for DataLoader shared memory
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_VISIBLE_DEVICES=0
      - PYTHONPATH=/workspace
      - DATASET=/workspace/DATASET  # Path resolution for datasets
    volumes:
      - ./DATASET:/workspace/DATASET
      - /mnt/mqdet-output:/workspace/OUTPUT        # <-- move OUTPUT to big host mount (see gcp_setup below)
      - ./MODEL:/workspace/MODEL
      - ./configs:/workspace/configs
      - ./tools:/workspace/tools
      - ./maskrcnn_benchmark:/workspace/maskrcnn_benchmark
      - ./groundingdino_new:/workspace/groundingdino_new
      - ./extract_queries.sh:/workspace/extract_queries.sh
      - ./train.sh:/workspace/train.sh
      - ./evaluate.sh:/workspace/evaluate.sh
      - ./cache:/workspace/.cache                  # pip/torch cache on a bind mount
    logging:                                       # keep container logs from eating disk
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "8888:8888"
      - "6006:6006"
    stdin_open: true
    tty: true
    working_dir: /workspace
    command: /bin/bash
