# MQ-Det Configuration for Connectors Dataset
# Based on official mq-glip-t.yaml but adapted for small custom dataset

MODEL:
  META_ARCHITECTURE: "GeneralizedVLRCNN_New"
  WEIGHT: "MODEL/glip_tiny_model_o365_goldg_cc_sbu.pth"
  RPN_ONLY: True
  RPN_ARCHITECTURE: "VLDYHEAD"

  BACKBONE:
    CONV_BODY: "SWINT-FPN-RETINANET"
    OUT_CHANNELS: 256
    FREEZE_CONV_BODY_AT: -1

  LANGUAGE_BACKBONE:
    FREEZE: False
    TOKENIZER_TYPE: "bert-base-uncased"
    MODEL_TYPE: "bert-base-uncased"
    MASK_SPECIAL: False

  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.125, 0.0625, 0.03125, 0.015625, 0.0078125)
    POOLER_SAMPLING_RATIO: 0

  DYHEAD:
    CHANNELS: 256
    NUM_CONVS: 6
    USE_GN: True
    USE_DYRELU: True
    USE_DFCONV: True
    USE_DYFUSE: True
    TOPK: 9
    SCORE_AGG: "MEAN"
    LOG_SCALE: 0.0

    FUSE_CONFIG:
      EARLY_FUSE_ON: True
      TYPE: "MHA-B"
      USE_CLASSIFICATION_LOSS: False
      USE_TOKEN_LOSS: False
      USE_CONTRASTIVE_ALIGN_LOSS: False
      USE_DOT_PRODUCT_TOKEN_LOSS: True
      USE_LAYER_SCALE: True
      CLAMP_MIN_FOR_UNDERFLOW: True
      CLAMP_MAX_FOR_OVERFLOW: True

  RPN:
    USE_FPN: True
    ANCHOR_SIZES: (64, 128, 256, 512, 1024)
    ANCHOR_STRIDE: (8, 16, 32, 64, 128)
    ASPECT_RATIOS: (1.0,)
    SCALES_PER_OCTAVE: 1

DATASETS:
  TRAIN: ("connectors_grounding_train",)
  TEST: ("connectors_grounding_val",)
  FEW_SHOT: 0

INPUT:
  MIN_SIZE_TRAIN: 800  # Increased for better accuracy (A100 can handle it)
  MAX_SIZE_TRAIN: 1333  # Standard resolution
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333

AUGMENT:
  MULT_MIN_SIZE_TRAIN: (480, 560, 640, 720, 800)  # More scale variation
  BRIGHTNESS: 0.2      # Add brightness augmentation
  CONTRAST: 0.2        # Add contrast augmentation
  SATURATION: 0.2      # Add color variation
  HUE: 0.1             # Slight hue variation

DATALOADER:
  SIZE_DIVISIBILITY: 32
  NUM_WORKERS: 2        # keep it modest in containers


SOLVER:
  OPTIMIZER: "ADAMW"
  BASE_LR: 0.0001  # Reduced from 0.0002 (adjusted for smaller batch)
  LANG_LR: 0.0001
  WEIGHT_DECAY: 0.0001
  STEPS: (0.67, 0.89)
  MAX_EPOCH: 100  # Dramatically increased - small datasets need more epochs
  IMS_PER_BATCH: 4  # Reduced from 8 to 4 for high resolution (800x1333)
  WARMUP_ITERS: 200  # Longer warmup for stability
  WARMUP_FACTOR: 0.001
  USE_AMP: True
  MODEL_EMA: 0.999
  CHECKPOINT_PER_EPOCH: 0.1   # Save more frequently (every 10 epochs)
  CHECKPOINT_PERIOD: 99999999  # keep large, we use per-epoch cadence
  TUNING_HIGHLEVEL_OVERRIDE: "vision_query"
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 1.0
    NORM_TYPE: 2.0

GLIPKNOW:
  PARALLEL_LANGUAGE_INPUT: False
  LAN_FEATURE_AGG_TYPE: "first"
  KNOWLEDGE_FILE: ""
  KNOWLEDGE_TYPE: ""

VISION_QUERY:
  ENABLED: True
  QUERY_BANK_PATH: 'MODEL/connectors_query_5000_sel_tiny.pth'
  PURE_TEXT_RATE: 0.
  TEXT_DROPOUT: 0.3  # Reduced dropout to retain more information
  VISION_SCALE: 1.0
  NUM_QUERY_PER_CLASS: 10  # Increased from 5 to 10 for better coverage
  RANDOM_KSHOT: False
  ADD_ADAPT_LAYER: False
  CONDITION_GATE: True
  NONLINEAR_GATE: True
  NO_CAT: True

TEST:
  EVAL_TASK: 'detection'
  CHUNKED_EVALUATION: -1
  IMS_PER_BATCH: 4

OUTPUT_DIR: 'OUTPUT/MQ-GLIP-TINY-CONNECTORS/'
