# MQ-Det Configuration for Connectors Dataset
# Based on official mq-glip-t.yaml but adapted for small custom dataset

MODEL:
  META_ARCHITECTURE: "GeneralizedVLRCNN_New"
  WEIGHT: "MODEL/glip_tiny_model_o365_goldg_cc_sbu.pth"
  RPN_ONLY: True
  RPN_ARCHITECTURE: "VLDYHEAD"

  BACKBONE:
    CONV_BODY: "SWINT-FPN-RETINANET"
    OUT_CHANNELS: 256
    FREEZE_CONV_BODY_AT: -1

  LANGUAGE_BACKBONE:
    FREEZE: False
    TOKENIZER_TYPE: "bert-base-uncased"
    MODEL_TYPE: "bert-base-uncased"
    MASK_SPECIAL: False

  DYHEAD:
    CHANNELS: 256
    NUM_CONVS: 6
    USE_GN: True
    USE_DYRELU: True
    USE_DFCONV: True
    USE_DYFUSE: True
    TOPK: 9
    SCORE_AGG: "MEAN"
    LOG_SCALE: 0.0

    FUSE_CONFIG:
      EARLY_FUSE_ON: True
      TYPE: "MHA-B"
      USE_CLASSIFICATION_LOSS: False
      USE_TOKEN_LOSS: False
      USE_CONTRASTIVE_ALIGN_LOSS: False
      USE_DOT_PRODUCT_TOKEN_LOSS: True
      USE_LAYER_SCALE: True
      CLAMP_MIN_FOR_UNDERFLOW: True
      CLAMP_MAX_FOR_OVERFLOW: True

  RPN:
    USE_FPN: True
    ANCHOR_SIZES: (64, 128, 256, 512, 1024)
    ANCHOR_STRIDE: (8, 16, 32, 64, 128)
    ASPECT_RATIOS: (1.0,)
    SCALES_PER_OCTAVE: 1

DATASETS:
  TRAIN: ("connectors_grounding_train",)
  TEST: ("connectors_grounding_val",)
  FEW_SHOT: 0

INPUT:
  MIN_SIZE_TRAIN: (800,)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333

DATALOADER:
  SIZE_DIVISIBILITY: 32

SOLVER:
  OPTIMIZER: "ADAMW"
  BASE_LR: 0.00001  # Reduced for small dataset
  LANG_LR: 0.00001
  WEIGHT_DECAY: 0.0001
  STEPS: (0.67, 0.89)
  MAX_EPOCH: 10  # Reduced for small dataset
  IMS_PER_BATCH: 4  # Reduced for single GPU
  WARMUP_ITERS: 100
  WARMUP_FACTOR: 0.001
  USE_AMP: True
  MODEL_EMA: 0.999
  CHECKPOINT_PERIOD: 99999999
  CHECKPOINT_PER_EPOCH: 2.0
  TUNING_HIGHLEVEL_OVERRIDE: "vision_query"
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 1.0
    NORM_TYPE: 2.0

GLIPKNOW:
  PARALLEL_LANGUAGE_INPUT: False
  LAN_FEATURE_AGG_TYPE: "first"
  KNOWLEDGE_FILE: ""
  KNOWLEDGE_TYPE: ""

VISION_QUERY:
  ENABLED: True
  QUERY_BANK_PATH: 'MODEL/connectors_query_5000_sel_tiny.pth'
  PURE_TEXT_RATE: 0.
  TEXT_DROPOUT: 0.4
  VISION_SCALE: 1.0
  NUM_QUERY_PER_CLASS: 5
  RANDOM_KSHOT: False
  ADD_ADAPT_LAYER: False
  CONDITION_GATE: True
  NONLINEAR_GATE: True
  NO_CAT: True

TEST:
  EVAL_TASK: 'detection'
  CHUNKED_EVALUATION: -1
  IMS_PER_BATCH: 4

OUTPUT_DIR: 'OUTPUT/MQ-GLIP-TINY-CONNECTORS/'
