DATASETS:
  TEST: ("connectors_grounding_val",)
  TRAIN_DATASETNAME_SUFFIX: "_vision_query"
  TEST_DATASETNAME_SUFFIX: ""
  FEW_SHOT: 0

MODEL:
  RPN:
    POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    DETECTIONS_PER_IMG: 100
    SCORE_THRESH_TEST: 0.0
    NMS: 0.5

DATASETS:
  GENERAL_COPY_PASTE_PROB: 0.0
  GENERAL_COPY_PASTE_PROB_TEST: 0.0

TEST:
  EVAL_TASK: detection
  IMS_PER_BATCH: 1

VISION_QUERY:
  ENABLED: True
  QUERY_BANK_PATH: "MODEL/connectors_query_5_pool7_sel_tiny.pth"
  NUM_QUERY_PER_CLASS: 5