DATASETS:
  TEST: ("fd4_ini_grounding_val",)
  TRAIN_DATASETNAME_SUFFIX: ""
  TEST_DATASETNAME_SUFFIX: ""
  FEW_SHOT: 0

MODEL:
  RPN:
    POST_NMS_TOP_N_TEST: 1000

TEST:
  EVAL_TASK: detection
  IMS_PER_BATCH: 1

VISION_QUERY:
  ENABLED: True
  QUERY_BANK_PATH: "MODEL/fd4_ini_query_5_pool7_sel_tiny.pth"
  NUM_QUERY_PER_CLASS: 5
